
# BASELINE NIGHTS - stas combined - AM - 31.03.2021

# the script combines files generated by Sleep Python (VisBrain) toolbox after sleep staging the sleep data

library(stringr)
library (stringi)

setwd("C:\\Users\\adria\\Desktop\\PhD\\Rrr\\sleep\\sleep_stats\\data\\baseline_nights_stats") #set directory

getwd()

files <-dir(path = "C:\\Users\\adria\\Desktop\\PhD\\Rrr\\sleep\\sleep_stats\\data\\baseline_nights_stats", recursive = TRUE,include.dirs = TRUE,pattern = "^statsinfo(.*)csv$")
print (files)

for (k in 1:length(files))

{
  
my_data <- read.csv(files[k], header = FALSE)
  
# transpose

df <- as.data.frame(t(my_data))
df

names(df) <- df[1, ]
df <- df[-1, ]
df

# extract ppt ID from the file name
ID_1 <-sub("*statsinfo_baseline_+","", files)  
save.name <- sub("_AM.csv","", ID_1)  
form = sprintf('%s', save.name)
form

sleep <- data.frame('ID'= form[k],'which_night_1_Baseline_2_Recovery'='1','TIB_Baseline'=df$TIB, 'TDT_Baseline'=df$TDT, 'wake_Baseline'=df$W, 'N1_Baseline'=df$N1, 
                    'N2_Baseline'=df$N2, 'N3_Baseline'=df$N3, 'REM_Baseline'=df$REM,'artefacts_Baseline'=df$Art, 'Latency_to_N1_Baseline'=df$LatN1, 
                    'Latency_to_N2_Baseline'=df$LatN2, 'Latency_to_N3_Baseline'=df$LatN3, 'Latency_to_REM_Baseline'=df$LatREM, 'SPT_Baseline'=df$SPT,
                    'WASO_Baseline'=df$WASO, 'TST_Baseline'=df$TST, 'SE_Baseline'=df$SE, 'units_Baseline'=df$Units)
sleep

form = files
pathOut= ("C:\\Users\\adria\\Desktop\\PhD\\Rrr\\sleep\\sleep_stats\\outcomes\\baseline_nights\\")
write.csv(sleep, paste(pathOut,file = form[k]),row.names=F)


}

###### merge all the outcomes into one large database 

setwd("C:\\Users\\adria\\Desktop\\PhD\\Rrr\\sleep\\sleep_stats\\outcomes\\baseline_nights\\") #set directory

# select file names to be merged, i.e., outcomes of the for loop above

srosia <- list.files (path="C:\\Users\\adria\\Desktop\\PhD\\Rrr\\sleep\\sleep_stats\\outcomes\\baseline_nights\\", pattern = "statsinfo")

print(srosia)

# lapply returns a list of the same length as X

daisy <- lapply(srosia,function(l) {read.csv(l)
})
daisy

# merging together all files 

sleep_staging_outcomes <- do.call (rbind.data.frame, daisy)

write.csv (sleep_staging_outcomes,"C:\\Users\\adria\\Desktop\\PhD\\Rrr\\sleep\\sleep_stats\\outcomes\\sleep_staging_outcomes_Baseline_Night_AM_31.03.2021.csv")

