
# RECOVERY NIGHTS - stas combined - AM - 31.03.2021

# the script combines files generated by Sleep Python (VisBrain) toolbox after sleep staging the sleep data

library(stringr)
library (stringi)

setwd("C:\\Users\\adria\\Desktop\\PhD\\Rrr\\sleep\\sleep_stats\\data\\recovery_nights_stats") #set directory

getwd()

files <-dir(path = "C:\\Users\\adria\\Desktop\\PhD\\Rrr\\sleep\\sleep_stats\\data\\recovery_nights_stats", recursive = TRUE,include.dirs = TRUE,pattern = "^APO(.*)csv$")
print (files)

for (k in 1:length(files))
  
{
  
  my_data <- read.csv(files[k], header = FALSE)
  my_data
  
  # transpose
  
  df <- as.data.frame(t(my_data))
  df
  
  names(df) <- df[1, ]
  df <- df[-1, ]
  df
  
  # extract ppt ID from the file name
  ID_1 <-sub("_statsinfo_Recovery_Night_AM.csv","", files)  
  ID_1
  form = sprintf('%s', ID_1)
  form
  
  sleep <- data.frame('ID'= form[k],'which_night_1_Baseline_2_Recovery'='2','TIB_Recovery'=df$TIB, 'TDT_Recovery'=df$TDT, 'wake_Recovery'=df$W, 'N1_Recovery'=df$N1, 
                      'N2_Recovery'=df$N2, 'N3_Recovery'=df$N3, 'REM_Recovery'=df$REM,'artefacts_Recovery'=df$Art, 'Latency_to_N1_Recovery'=df$LatN1, 
                      'Latency_to_N2_Recovery'=df$LatN2, 'Latency_to_N3_Recovery'=df$LatN3, 'Latency_to_REM_Recovery'=df$LatREM, 'SPT_Recovery'=df$SPT,
                      'WASO_Recovery'=df$WASO, 'TST_Recovery'=df$TST, 'SE_Recovery'=df$SE, 'units_Recovery'=df$Units)
  sleep
  
  form = files
  pathOut= ("C:\\Users\\adria\\Desktop\\PhD\\Rrr\\sleep\\sleep_stats\\outcomes\\recovery_nights\\")
  write.csv(sleep, paste(pathOut,file = form[k]),row.names=F)
  
  
}

###### merge all the outcomes into one large database 

setwd("C:\\Users\\adria\\Desktop\\PhD\\Rrr\\sleep\\sleep_stats\\outcomes\\recovery_nights\\") #set directory

# select file names to be merged, i.e., outcomes of the for loop above

srosia <- list.files (path="C:\\Users\\adria\\Desktop\\PhD\\Rrr\\sleep\\sleep_stats\\outcomes\\recovery_nights\\", pattern = "statsinfo")

print(srosia)

# lapply returns a list of the same length as X

daisy <- lapply(srosia,function(l) {read.csv(l)
})
daisy

# merging together all files 

sleep_staging_outcomes <- do.call (rbind.data.frame, daisy)

write.csv (sleep_staging_outcomes,"C:\\Users\\adria\\Desktop\\PhD\\Rrr\\sleep\\sleep_stats\\outcomes\\sleep_staging_outcomes_Recovery_Night_AM_31.03.2021.csv")

