
# Sea Hero Quest (SHQ) - analysis - wayfinding part - final - Adriana Michalak - 15.12.2020

# the script is joining diffrent .csv files generated by the SHQ Matlab script written by Antoine Coutrot (the existing code was updated for accounting for my repeated measures on 14.12.2020); Antoine's script is the only one (I am aware of) extracting the wayfinding distance information (heat maps analysis)
# 'ppt' = participant

library(dplyr)
library(readr)
library (tidyverse)
library(stringr)
#install.packages("stringr")
#devtools::install_github("tidyverse/stringr")

# combine outcome spreadsheets generated by the Matlab Code (one file per ppt); we will save as a data frame (df)

df <- list.files(path="C:\\Users\\adria\\Desktop\\PhD\\Rrr\\SHQ\\Data\\MN", full.names = TRUE) %>% 
  lapply(read_csv) %>% 
  bind_rows 

# THIS SECTION (save.name lines) WILL NEED TO BE ADAPTED TO YOURS ID

way <- str_replace_all(df$subject, "practice", "t0") # for sake of consistent naming system I've replaced "practice" with "t0"

save.name1 <-sub(".json", "", way)
save.name1
save.name2 <- sub(" -.*", "", save.name1) # ppt ID and the t 
save.name2
save.name3 <- sub (".*/", "", save.name1)
save.name3
save.name4 <- sub ("_attempt.*", "", save.name3) # level ID 
save.name4
save.name <- paste(save.name2, save.name4, sep = "_") # file name
save.name
save.name5 <-  sub ("_t.*", "", save.name1) # ppt ID only 
save.name5
save.name6 <- sub (".*_t", "", save.name2) # t session only 
save.name6

# let's create a new df with all relevant variables of interest

SHQ_MN <- data.frame ('Participant_ID'= save.name5,'protocol_1_SD_2_MN'=2,'session_number'=save.name6, 'level_ID'= df$level,'attempt'=df$attempt,'distance'= df$distance, 'distance_normalized'=df$distance_normalised,
                      'map_duration'=df$duration)
SHQ_MN

SHQ_MN_wayfinding<- na.omit(SHQ_MN)

write.csv(SHQ_MN_wayfinding,"C:\\Users\\adria\\Desktop\\PhD\\Rrr\\SHQ\\Outcomes\\SHQ_MN_SD\\SHQ_outcomes_wayfinding_MN_AM_15.12.2020.csv",row.names=F) # it will generate the .csv with the outcomes of interest for each participants; we will merge them later

################################################################################################################
# I'm repeating this step because I've two different conditions, i.e., MultiNap (MN) and Sleep Deprivation (SD)
################################################################################################################

df_SD <- list.files(path="C:\\Users\\adria\\Desktop\\PhD\\Rrr\\SHQ\\Data\\SD", full.names = TRUE) %>% 
  lapply(read_csv) %>% 
  bind_rows 

way_SD <- str_replace_all(df_SD$subject, "practice", "t0")

save.name1 <-sub(".json", "", way_SD)
save.name1
save.name2 <- sub(" -.*", "", save.name1) # ppt ID and the t 
save.name2
save.name3 <- sub (".*/", "", save.name1)
save.name3
save.name4 <- sub ("_attempt.*", "", save.name3) # level ID 
save.name4
save.name <- paste(save.name2, save.name4, sep = "_") # file name
save.name
save.name5 <-  sub ("_t.*", "", save.name1) # ppt ID only 
save.name5
save.name6 <- sub (".*_t", "", save.name2) # t session only 
save.name6

SHQ_SD <- data.frame ('Participant_ID'= save.name5,'protocol_1_SD_2_MN'=1,'session_number'=save.name6, 'level_ID'= df_SD$level,'attempt'=df_SD$attempt,'distance'= df_SD$distance, 'distance_normalized'=df_SD$distance_normalised,
                      'map_duration'=df_SD$duration)


SHQ_SD

SHQ_SD_wayfinding<- na.omit(SHQ_SD) # for some reason Matlab script generates a lot of NaN, therefore, this step is important to remove the missing values; however, be careful to do not remove  relevant  data as the na.omit will remove full row if even one NaN (missing value) is present

write.csv(SHQ_SD_wayfinding,"C:\\Users\\adria\\Desktop\\PhD\\Rrr\\SHQ\\Outcomes\\SHQ_MN_SD\\SHQ_outcomes_wayfinding_SD_AM_15.12.2020.csv",row.names=F) # it will generate the .csv with the outcomes of interest for each participants; we will merge them later


######################################################################
# Combine MN and SD (I have two different conditions in my project)
######################################################################

combine_MN_SD <- list.files(path="C:\\Users\\adria\\Desktop\\PhD\\Rrr\\SHQ\\Outcomes\\SHQ_MN_SD\\", full.names = TRUE) %>% 
  lapply(read_csv) %>% 
  bind_rows 

combine_MN_SD <- data.frame(combine_MN_SD)

write.csv(combine_MN_SD,"C:\\Users\\adria\\Desktop\\PhD\\Rrr\\SHQ\\Outcomes\\SHQ_outcomes_wayfinding_all_AM_15.12.2020.csv",row.names=F) # it will generate the .csv with the outcomes of interest for each participants, we will merge them below

